### PR TITLE
Development

### PR DESCRIPTION
**Pull request by th3bluecarp**

### CODE REVIEW

**Comment by chris102994** [comment]
Hey I saw this after you had already closed it. I went ahead and added in your channels along with refactoring some code to scrape the EPG for the Snickelodeon channels. I was unable to find the EPG source for the MTV97. . . If you can find it let me know.
Commit with changes:
https://github.com/chris102994/docker-toonamiaftermath/commit/0b62ddf412e2aa62d7c7722ce5443285218ecb27

**Comment by th3bluecarp** [comment]
Hey, sorry about that. I've honestly never used Github before and was messing around with Github Desktop. I had forked your repo to mess around with adding stuff myself since I didn't want to mess up anything with yours. 

I didn't realize that MTV97 won't have an EPG because it just says "Music Videos" all the time, so that can be removed. 

I was just planning on messing around and I wanted to create the docker file and add it to Docker Hub so I could easily install on Unraid. It seems like your Docker Hub page for this doesn't contain the file.

**Comment by chris102994** [comment]
It's all good. You just showed me some channels I didn't know existed. 
If you know any more or ever scrape any others feel free to email me the details and I can add them to the project.
You're also right. I didn't have a Unraid template so I made one.
Hope you enjoy my project. I'm glad to see people using it!

**Comment by th3bluecarp** [comment]
Pinging you here as I don't want to open an issue, since it's most likely on my end. I've been trying for a year to get this thing running (in what free time I have) and have had no luck whatsoever. I know nothing about Docker and was trying to find some way to import it into my Unraid server. I gave up in that direction and finally just tried to do it with the Docker commands you have in the readme. The issue I'm running into now is nginx saying it can't open the error log file. Do you have any idea how I can fix / bypass this? Really all I want is a way to access just the .m3u and .xml to import into Channels.

`docker run --name=docker-toonamiaftermath -p 8085:8085 -v /mnt/user/cache/xteve_toon:/config --restart unless-stopped christopher102994/docker-toonamiaftermath:ubuntu-18-latest
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] 50-toonami-attrs: applying... 
[fix-attrs.d] 50-toonami-attrs: exited 0.
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-users-and-groups: executing... 
usermod: no changes
[cont-init.d] 01-users-and-groups: exited 0.
[cont-init.d] 05-init-mounted-folders: executing... 
[cont-init.d] 05-init-mounted-folders: exited 0.
[cont-init.d] 10-display-container-info: executing... 
[10-display-container-info]: 
-------------------------
# USER DEFINED VARIABLES:
-------------------------
LC_ALL=C.UTF-8
GROUPNAME=user
USERNAME=user
PUID=900
FIRST_RUN=TRUE
PGID=900
-------------------------
# UID/GID of user:
-------------------------
UID: 900
GID: 900
-------------------------
# FOLDER PERMISSIONS:
-------------------------
drwxr-xr-x 1 user user 58 Apr  7  2021 /app
drwxr-xr-x 1 user user 82 Jan  5 20:46 /config
drwxr-xr-x 1 user user 30 Apr  7  2021 /defaults
-------------------------
[cont-init.d] 10-display-container-info: exited 0.
[cont-init.d] 40-fix-toonami-attrs: executing... 
[cont-init.d] 40-fix-toonami-attrs: exited 0.
[cont-init.d] 50-first-run: executing... 
[cont-init.d] 50-first-run: exited 0.
[cont-init.d] 60-fix-nginx-config: executing... 
Ensuring proper NGINX configuration.
[cont-init.d] 60-fix-nginx-config: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[run]: The Package Manager is apt-get
[nginx]: Starting . . .
nginx: [alert] could not open error log file: open() "/var/log/nginx/error.log" failed (2: No such file or directory)`

**Comment by chris102994** [comment]
That's a harmless nginx issue you can ignore. I guess If I had time I could fix it but since it didn't hurt anything I never bothered with it.

I have an unRAID template here:

https://github.com/chris102994/docker-templates

**Comment by th3bluecarp** [comment]
DUDE. WOW!

I've been banging my head against a wall trying to get this working myself
for so long. I got it up and running finally using the template you made in
30 seconds.

I really appreciate it, thank you!

**Comment by chris102994** [comment]
You're welcome

**Pull request closed without merging**
